### ISSUE TITLE
Split all tests into unit and integration tests

### ISSUE THREAD

**Issue by Sh4kE** [Autostew/autostew#29]

**Comment by jardiacaj** [comment]
Maybe it would make sense to count only the coverage of unit tests.

**Comment by Sh4kE** [comment]
That would probably help. 

I think we don't have to split them on the filesystem. Maybe there are parameters to the test command to exclude some packages or something.

**Comment by jardiacaj** [comment]
The skifIf decorator could help :)

https://docs.djangoproject.com/en/1.9/topics/testing/tools/#skipping-tests

**Comment by Sh4kE** [comment]
I provided two new pycharm configurations, but they are set manually to our django apps unfortunatly. In bash one could simply say:
`./manage.py test autostew_*/tests/unit`
